Drop support for CentOS 7
omnivector-solutions/slurmdbd-operator pull request #19
Opened 2023-09-22 16:36 UTC by jaimesouza

## Description

Drop support for CentOS 7.

## How was the code tested?

The code was tested locally with LXD containers running Ubuntu 22.04.

## Related issues and/or tasks

> Link any related issues or project board tasks to this pull request.

## Checklist

- [x] I am the author of these changes, or I have the rights to submit them.
- [ ] I have added the relevant changes to the README and/or documentation.
- [x] I have self reviewed my own code.
- [ ] All requested changes and/or review comments have been resolved.

2023-09-26 14:09 UTC, NucciTheBoss requested changes
LGTM, just one minor comment.

2023-09-26 14:09 UTC, NucciTheBoss commented on dispatch
Similar to my comment https://github.com/omnivector-solutions/slurmctld-operator/pull/18#discussion_r1337269095 on your pull request against the slurmctld operator.

2023-09-26 14:28 UTC, jaimesouza commented on dispatch
That is right! Thanks @NucciTheBoss!

2023-09-29 15:39 UTC, NucciTheBoss approved these changes
LGTM! Nice work :tada:

2023-10-02 12:24 UTC, merged